import type { EditablePageSlug } from "./pageOverrides";

export type EditablePageDefinition = {
  slug: EditablePageSlug;
  title: string;
  routePath: string;
  textKeys: string[];
};

export const EDITABLE_PAGES: EditablePageDefinition[] = [
  {
    slug: "about",
    title: "Om",
    routePath: "/om",
    textKeys: [
      "about.hero.title",
      "about.hero.tagline",
      "about.started.title",
      "about.started.p1",
      "about.started.p2",
      "about.workshop.title",
      "about.workshop.p1",
      "about.workshop.p2",
      "about.quality.title",
      "about.quality.p1",
      "about.quality.p2",
      "about.principles.title",
      "about.principles.lead",
      "about.principles.bullets.singleSource",
      "about.principles.bullets.singleSourceBody",
      "about.principles.bullets.predictability",
      "about.principles.bullets.predictabilityBody",
      "about.principles.bullets.respect",
      "about.principles.bullets.respectBody",
      "about.principles.bullets.realWork",
      "about.principles.bullets.realWorkBody",
      "about.principles.outro",
      "about.principles.outroEm",
      "about.deliver.title",
      "about.deliver.p1",
      "about.deliver.linkLead",
      "about.deliver.linkCta",
      "about.direction.title",
      "about.direction.p1",
      "about.direction.linkLead",
      "about.direction.linkCta",
    ],
  },
  {
    slug: "services",
    title: "Tjenester / Idébank",
    routePath: "/idebank",
    textKeys: [
      "services.hero.title",
      "services.hero.tagline",
      "services.hero.p1",
      "services.hero.p2",
      "services.hero.back",
      "services.hero.contact",
      "services.model1.label",
      "services.model1.title",
      "services.model1.lead",
      "services.model1.bullets.b1Strong",
      "services.model1.bullets.b1",
      "services.model1.bullets.b2Strong",
      "services.model1.bullets.b2",
      "services.model1.bullets.b3Strong",
      "services.model1.bullets.b3",
      "services.model1.p1",
      "services.model1.cta",
      "services.model2.label",
      "services.model2.title",
      "services.model2.lead",
      "services.model2.bullets.b1Strong",
      "services.model2.bullets.b1",
      "services.model2.bullets.b2Strong",
      "services.model2.bullets.b2",
      "services.model2.bullets.b3Strong",
      "services.model2.bullets.b3",
      "services.model2.p1a",
      "services.model2.p1bStrong",
      "services.model2.p1c",
      "services.model2.submitEmailCta",
      "services.interesting.title",
      "services.interesting.lead",
      "services.interesting.bullets.b1",
      "services.interesting.bullets.b2",
      "services.interesting.bullets.b3",
      "services.interesting.bullets.b4",
      "services.interesting.exampleLead",
      "services.interesting.exampleCta",
    ],
  },
  {
    slug: "contact",
    title: "Kontakt",
    routePath: "/kontakt",
    textKeys: [
      "contact.title",
      "contact.tagline",
      "contact.emailLabel",
      "contact.phoneLabel",
    ],
  },
  {
    slug: "purchase",
    title: "Kjøpsvilkår",
    routePath: "/kjopsvilkar",
    textKeys: [
      "legal.purchase.title",
      "legal.purchase.intro",
      "legal.purchase.s1.title",
      "legal.purchase.s1.body",
      "legal.purchase.s2.title",
      "legal.purchase.s2.body",
      "legal.purchase.s3.title",
      "legal.purchase.s3.body",
      "legal.purchase.s4.title",
      "legal.purchase.s4.body",
      "legal.purchase.s5.title",
      "legal.purchase.s5.body",
      "legal.purchase.s6.title",
      "legal.purchase.s6.body",
      "legal.purchase.s7.title",
      "legal.purchase.s7.body",
      "legal.purchase.s8.title",
      "legal.purchase.s8.body",
    ],
  },
  {
    slug: "terms",
    title: "Brukervilkår",
    routePath: "/brukervilkar",
    textKeys: [
      "legal.terms.title",
      "legal.terms.intro",
      "legal.terms.s1.title",
      "legal.terms.s1.body",
      "legal.terms.s2.title",
      "legal.terms.s2.body",
      "legal.terms.s3.title",
      "legal.terms.s3.body",
      "legal.terms.s4.title",
      "legal.terms.s4.body",
      "legal.terms.s5.title",
      "legal.terms.s5.body",
      "legal.terms.s6.title",
      "legal.terms.s6.body",
    ],
  },
  {
    slug: "privacy",
    title: "Personvern",
    routePath: "/personvern",
    textKeys: [
      "legal.privacy.title",
      "legal.privacy.intro",
      "legal.privacy.s1.title",
      "legal.privacy.s1.body",
      "legal.privacy.s2.title",
      "legal.privacy.s2.lead",
      "legal.privacy.s2.bullets.0",
      "legal.privacy.s2.bullets.1",
      "legal.privacy.s2.bullets.2",
      "legal.privacy.s2.bullets.3",
      "legal.privacy.s3.title",
      "legal.privacy.s3.lead",
      "legal.privacy.s3.bullets.0",
      "legal.privacy.s3.bullets.1",
      "legal.privacy.s3.bullets.2",
      "legal.privacy.s3.bullets.3",
      "legal.privacy.s4.title",
      "legal.privacy.s4.body",
      "legal.privacy.s5.title",
      "legal.privacy.s5.body",
      "legal.privacy.s6.title",
      "legal.privacy.s6.body",
      "legal.privacy.s7.title",
      "legal.privacy.s7.body",
      "legal.privacy.s8.title",
      "legal.privacy.s8.body",
    ],
  },
  {
    slug: "refund",
    title: "Refusjon og klage",
    routePath: "/refusjon",
    textKeys: [
      "legal.refund.title",
      "legal.refund.intro",
      "legal.refund.s1.title",
      "legal.refund.s1.p1",
      "legal.refund.s1.bullets.0",
      "legal.refund.s1.bullets.1",
      "legal.refund.s1.p2",
      "legal.refund.s2.title",
      "legal.refund.s2.p1",
      "legal.refund.s2.bullets.0",
      "legal.refund.s2.bullets.1",
      "legal.refund.s3.title",
      "legal.refund.s3.body",
      "legal.refund.s4.title",
      "legal.refund.s4.body",
      "legal.refund.s5.title",
      "legal.refund.s5.lead",
      "legal.refund.s5.bodyAfterEmail",
      "legal.refund.s5.bullets.0",
      "legal.refund.s5.bullets.1",
      "legal.refund.s5.bullets.2",
      "legal.refund.s5.bullets.3",
    ],
  },
];
