export const LINKS = {
  mcl: "https://morningcoffeelabs.no",
  ms: "https://managesystem.no",
  progress: "https://progress.managesystem.no",
  kvittekGooglePlay: "https://play.google.com/store/apps/details?id=com.morningcoffeelabs.kvittek",
  kvittekAppStore: "https://apps.apple.com/no/app/kvittek/id6777185540",
  husketGooglePlay: "https://play.google.com/store/apps/details?id=no.morningcoffeelabs.husket&pcampaignid=web_share",
  findbackGooglePlay: "https://play.google.com/store/apps/details?id=com.morningcoffeelabs.findback",
  findbackAppStore: "https://apps.apple.com/us/app/findback-onetap/id6796313821",
  furyGooglePlay: "https://play.google.com/store/apps/details?id=com.morningcoffeelabs.furyo",
  furyAppStore: "https://apps.apple.com/us/app/fury-o/id6798349790",
  r4GooglePlay: "https://play.google.com/store/apps/details?id=com.morningcoffeelabs.r4",
  r4AppStore: "https://apps.apple.com/us/app/r4-easy-access/id6803176387",
  r4PeerPush: "https://peerpush.com/p/r4",
} as const;
